from ast import *
root = ListNode(SymbolNode("namespace"), 
  SymbolNode("Generator.PsxCore"), 
  ListNode(SymbolNode("class"), 
    SymbolNode("IType"), 
    ListNode(ListNode(SymbolNode("type"), 
        SymbolNode("InstructionClass`1"), 
        ListNode(SymbolNode("type"), 
          SymbolNode("IType"), ), ), ), 
    ListNode(SymbolNode("field"), 
      SymbolNode("Op"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Byte"), ), ), 
    ListNode(SymbolNode("field"), 
      SymbolNode("Rs"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Byte"), ), ), 
    ListNode(SymbolNode("field"), 
      SymbolNode("Rt"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Byte"), ), ), 
    ListNode(SymbolNode("field"), 
      SymbolNode("Imm"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("UInt16"), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode("Parse"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("IType"), ), 
        ListNode(SymbolNode("inst"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("UInt32"), ), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("ldc.i4.0"), ), 
        ListNode(SignedNode(0x2), 
          SymbolNode("stloc.0"), ), 
        ListNode(SignedNode(0x3), 
          SymbolNode("br.s"), 
          SignedNode(0x27), ), 
        ListNode(SignedNode(0x5), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x6), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x32), ), 
        ListNode(SignedNode(0x9), 
          SymbolNode("clt"), ), 
        ListNode(SignedNode(0xB), 
          SymbolNode("stloc.1"), ), 
        ListNode(SignedNode(0xC), 
          SymbolNode("ldloc.1"), ), 
        ListNode(SignedNode(0xD), 
          SymbolNode("brfalse.s"), 
          SignedNode(0x18), ), 
        ListNode(SignedNode(0xF), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x10), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Console"), ), 
            ListNode(SymbolNode("WriteLine"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x15), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x16), 
          SymbolNode("br.s"), 
          SignedNode(0x22), ), 
        ListNode(SignedNode(0x18), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x19), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0xA), ), 
        ListNode(SignedNode(0x1B), 
          SymbolNode("add"), ), 
        ListNode(SignedNode(0x1C), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Console"), ), 
            ListNode(SymbolNode("WriteLine"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x21), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x22), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x23), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x24), 
          SymbolNode("ldc.i4.1"), ), 
        ListNode(SignedNode(0x25), 
          SymbolNode("add"), ), 
        ListNode(SignedNode(0x26), 
          SymbolNode("stloc.0"), ), 
        ListNode(SignedNode(0x27), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x28), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x64), ), 
        ListNode(SignedNode(0x2A), 
          SymbolNode("clt"), ), 
        ListNode(SignedNode(0x2C), 
          SymbolNode("stloc.2"), ), 
        ListNode(SignedNode(0x2D), 
          SymbolNode("ldloc.2"), ), 
        ListNode(SignedNode(0x2E), 
          SymbolNode("brtrue.s"), 
          SignedNode(0x5), ), 
        ListNode(SignedNode(0x30), 
          SymbolNode("newobj"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            ListNode(SymbolNode(".ctor"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), ), ), 
        ListNode(SignedNode(0x35), 
          SymbolNode("dup"), ), 
        ListNode(SignedNode(0x36), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x37), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x1F), ), 
        ListNode(SignedNode(0x39), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x1A), ), 
        ListNode(SignedNode(0x3B), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("Bitfield"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Byte"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x40), 
          SymbolNode("stfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            SymbolNode("Op"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x45), 
          SymbolNode("dup"), ), 
        ListNode(SignedNode(0x46), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x47), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x19), ), 
        ListNode(SignedNode(0x49), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x15), ), 
        ListNode(SignedNode(0x4B), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("Bitfield"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Byte"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x50), 
          SymbolNode("stfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            SymbolNode("Rs"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x55), 
          SymbolNode("dup"), ), 
        ListNode(SignedNode(0x56), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x57), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x14), ), 
        ListNode(SignedNode(0x59), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x10), ), 
        ListNode(SignedNode(0x5B), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("Bitfield"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Byte"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x60), 
          SymbolNode("stfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            SymbolNode("Rt"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x65), 
          SymbolNode("dup"), ), 
        ListNode(SignedNode(0x66), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x67), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0xF), ), 
        ListNode(SignedNode(0x69), 
          SymbolNode("ldc.i4.0"), ), 
        ListNode(SignedNode(0x6A), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("Bitfield"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt16"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x6F), 
          SymbolNode("stfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            SymbolNode("Imm"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt16"), ), ), ), 
        ListNode(SignedNode(0x74), 
          SymbolNode("stloc.3"), ), 
        ListNode(SignedNode(0x75), 
          SymbolNode("br.s"), 
          SignedNode(0x77), ), 
        ListNode(SignedNode(0x77), 
          SymbolNode("ldloc.3"), ), 
        ListNode(SignedNode(0x78), 
          SymbolNode("ret"), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode("Match"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Boolean"), ), 
        ListNode(SymbolNode("insn"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("IType"), ), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("ldarg.1"), ), 
        ListNode(SignedNode(0x2), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            SymbolNode("Op"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x8), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            SymbolNode("Op"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0xD), 
          SymbolNode("ceq"), ), 
        ListNode(SignedNode(0xF), 
          SymbolNode("stloc.0"), ), 
        ListNode(SignedNode(0x10), 
          SymbolNode("br.s"), 
          SignedNode(0x12), ), 
        ListNode(SignedNode(0x12), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x13), 
          SymbolNode("ret"), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode(".ctor"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Void"), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("InstructionClass`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("IType"), ), ), 
            ListNode(SymbolNode(".ctor"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), ), ), 
        ListNode(SignedNode(0x6), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("ret"), ), ), ), ), 
  ListNode(SymbolNode("class"), 
    SymbolNode("ITypeAttribute"), 
    ListNode(ListNode(SymbolNode("type"), 
        SymbolNode("InstructionAttribute"), ), ), 
    ListNode(SymbolNode("property"), 
      SymbolNode("InstructionType"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Type"), ), 
      ListNode(SymbolNode("method"), 
        SymbolNode("get_InstructionType"), 
        ListNode(ListNode(SymbolNode("type"), 
            SymbolNode("Type"), ), ), 
        ListNode(SymbolNode("body"), 
          ListNode(SignedNode(0x0), 
            SymbolNode("ldtoken"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), ), 
          ListNode(SignedNode(0x5), 
            SymbolNode("call"), 
            ListNode(SymbolNode("method"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Type"), ), 
              ListNode(SymbolNode("GetTypeFromHandle"), ), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Type"), ), 
              ListNode(SymbolNode("type"), 
                SymbolNode("RuntimeTypeHandle"), ), ), ), 
          ListNode(SignedNode(0xA), 
            SymbolNode("ret"), ), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode("get_InstructionType"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Type"), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("ldtoken"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("IType"), ), ), 
        ListNode(SignedNode(0x5), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Type"), ), 
            ListNode(SymbolNode("GetTypeFromHandle"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Type"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RuntimeTypeHandle"), ), ), ), 
        ListNode(SignedNode(0xA), 
          SymbolNode("ret"), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode(".ctor"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Void"), ), 
        ListNode(SymbolNode("op"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("Byte"), ), ), 
        ListNode(SymbolNode("disasm"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("String"), ), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("InstructionAttribute"), ), 
            ListNode(SymbolNode(".ctor"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), ), ), 
        ListNode(SignedNode(0x6), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x8), 
          SymbolNode("ret"), ), ), ), ), 
  ListNode(SymbolNode("class"), 
    SymbolNode("RType"), 
    ListNode(ListNode(SymbolNode("type"), 
        SymbolNode("InstructionClass`1"), 
        ListNode(SymbolNode("type"), 
          SymbolNode("RType"), ), ), ), 
    ListNode(SymbolNode("field"), 
      SymbolNode("Op"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Byte"), ), ), 
    ListNode(SymbolNode("field"), 
      SymbolNode("Rs"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Byte"), ), ), 
    ListNode(SymbolNode("field"), 
      SymbolNode("Rt"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Byte"), ), ), 
    ListNode(SymbolNode("field"), 
      SymbolNode("Rd"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Byte"), ), ), 
    ListNode(SymbolNode("field"), 
      SymbolNode("Shamt"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Byte"), ), ), 
    ListNode(SymbolNode("field"), 
      SymbolNode("Funct"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Byte"), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode("Parse"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("RType"), ), 
        ListNode(SymbolNode("inst"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("UInt32"), ), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("newobj"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            ListNode(SymbolNode(".ctor"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), ), ), 
        ListNode(SignedNode(0x6), 
          SymbolNode("dup"), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x8), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x1F), ), 
        ListNode(SignedNode(0xA), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x1A), ), 
        ListNode(SignedNode(0xC), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("Bitfield"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Byte"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x11), 
          SymbolNode("stfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Op"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x16), 
          SymbolNode("dup"), ), 
        ListNode(SignedNode(0x17), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x18), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x19), ), 
        ListNode(SignedNode(0x1A), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x15), ), 
        ListNode(SignedNode(0x1C), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("Bitfield"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Byte"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x21), 
          SymbolNode("stfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Rs"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x26), 
          SymbolNode("dup"), ), 
        ListNode(SignedNode(0x27), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x28), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x14), ), 
        ListNode(SignedNode(0x2A), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x10), ), 
        ListNode(SignedNode(0x2C), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("Bitfield"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Byte"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x31), 
          SymbolNode("stfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Rt"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x36), 
          SymbolNode("dup"), ), 
        ListNode(SignedNode(0x37), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x38), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0xF), ), 
        ListNode(SignedNode(0x3A), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0xB), ), 
        ListNode(SignedNode(0x3C), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("Bitfield"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Byte"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x41), 
          SymbolNode("stfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Rd"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x46), 
          SymbolNode("dup"), ), 
        ListNode(SignedNode(0x47), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x48), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0xA), ), 
        ListNode(SignedNode(0x4A), 
          SymbolNode("ldc.i4.6"), ), 
        ListNode(SignedNode(0x4B), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("Bitfield"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Byte"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x50), 
          SymbolNode("stfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Shamt"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x55), 
          SymbolNode("dup"), ), 
        ListNode(SignedNode(0x56), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x57), 
          SymbolNode("ldc.i4.5"), ), 
        ListNode(SignedNode(0x58), 
          SymbolNode("ldc.i4.0"), ), 
        ListNode(SignedNode(0x59), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("Bitfield"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Byte"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x5E), 
          SymbolNode("stfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Funct"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x63), 
          SymbolNode("stloc.0"), ), 
        ListNode(SignedNode(0x64), 
          SymbolNode("br.s"), 
          SignedNode(0x66), ), 
        ListNode(SignedNode(0x66), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x67), 
          SymbolNode("ret"), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode("Match"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Boolean"), ), 
        ListNode(SymbolNode("insn"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("RType"), ), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("ldarg.1"), ), 
        ListNode(SignedNode(0x2), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Op"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x8), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Op"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0xD), 
          SymbolNode("bne.un.s"), 
          SignedNode(0x1F), ), 
        ListNode(SignedNode(0xF), 
          SymbolNode("ldarg.1"), ), 
        ListNode(SignedNode(0x10), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Funct"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x15), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x16), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Funct"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x1B), 
          SymbolNode("ceq"), ), 
        ListNode(SignedNode(0x1D), 
          SymbolNode("br.s"), 
          SignedNode(0x20), ), 
        ListNode(SignedNode(0x1F), 
          SymbolNode("ldc.i4.0"), ), 
        ListNode(SignedNode(0x20), 
          SymbolNode("stloc.0"), ), 
        ListNode(SignedNode(0x21), 
          SymbolNode("br.s"), 
          SignedNode(0x23), ), 
        ListNode(SignedNode(0x23), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x24), 
          SymbolNode("ret"), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode(".ctor"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Void"), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("ldc.i4.5"), ), 
        ListNode(SignedNode(0x2), 
          SymbolNode("stfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Rd"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x8), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("InstructionClass`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("RType"), ), ), 
            ListNode(SymbolNode(".ctor"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), ), ), 
        ListNode(SignedNode(0xD), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0xE), 
          SymbolNode("ret"), ), ), ), ), 
  ListNode(SymbolNode("class"), 
    SymbolNode("RTypeAttribute"), 
    ListNode(ListNode(SymbolNode("type"), 
        SymbolNode("InstructionAttribute"), ), ), 
    ListNode(SymbolNode("property"), 
      SymbolNode("InstructionType"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Type"), ), 
      ListNode(SymbolNode("method"), 
        SymbolNode("get_InstructionType"), 
        ListNode(ListNode(SymbolNode("type"), 
            SymbolNode("Type"), ), ), 
        ListNode(SymbolNode("body"), 
          ListNode(SignedNode(0x0), 
            SymbolNode("ldtoken"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), ), 
          ListNode(SignedNode(0x5), 
            SymbolNode("call"), 
            ListNode(SymbolNode("method"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Type"), ), 
              ListNode(SymbolNode("GetTypeFromHandle"), ), 
              ListNode(SymbolNode("type"), 
                SymbolNode("Type"), ), 
              ListNode(SymbolNode("type"), 
                SymbolNode("RuntimeTypeHandle"), ), ), ), 
          ListNode(SignedNode(0xA), 
            SymbolNode("ret"), ), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode("get_InstructionType"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Type"), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("ldtoken"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("RType"), ), ), 
        ListNode(SignedNode(0x5), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Type"), ), 
            ListNode(SymbolNode("GetTypeFromHandle"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Type"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RuntimeTypeHandle"), ), ), ), 
        ListNode(SignedNode(0xA), 
          SymbolNode("ret"), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode(".ctor"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Void"), ), 
        ListNode(SymbolNode("op"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("Byte"), ), ), 
        ListNode(SymbolNode("disasm"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("String"), ), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("InstructionAttribute"), ), 
            ListNode(SymbolNode(".ctor"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), ), ), 
        ListNode(SignedNode(0x6), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x8), 
          SymbolNode("ret"), ), ), ), ), 
  ListNode(SymbolNode("class"), 
    SymbolNode("PsxRegs"), 
    ListNode(ListNode(SymbolNode("type"), 
        SymbolNode("Registers`1"), 
        ListNode(SymbolNode("type"), 
          SymbolNode("UInt32"), ), ), ), 
    ListNode(SymbolNode("property"), 
      SymbolNode("Count"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("Int32"), ), 
      ListNode(SymbolNode("method"), 
        SymbolNode("get_Count"), 
        ListNode(ListNode(SymbolNode("type"), 
            SymbolNode("Int32"), ), ), 
        ListNode(SymbolNode("body"), 
          ListNode(SignedNode(0x0), 
            SymbolNode("ldc.i4.s"), 
            SignedNode(0x20), ), 
          ListNode(SignedNode(0x2), 
            SymbolNode("ret"), ), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode("get_Count"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Int32"), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("ldc.i4.s"), 
          SignedNode(0x20), ), 
        ListNode(SignedNode(0x2), 
          SymbolNode("ret"), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode(".ctor"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Void"), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Registers`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), 
            ListNode(SymbolNode(".ctor"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), ), ), 
        ListNode(SignedNode(0x6), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("ret"), ), ), ), ), 
  ListNode(SymbolNode("class"), 
    SymbolNode("PsxCpu"), 
    ListNode(ListNode(SymbolNode("type"), 
        SymbolNode("Cpu`1"), 
        ListNode(SymbolNode("type"), 
          SymbolNode("UInt32"), ), ), ), 
    ListNode(SymbolNode("field"), 
      SymbolNode("Gpr"), 
      ListNode(SymbolNode("type"), 
        SymbolNode("PsxRegs"), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode("Dispatch"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Boolean"), ), 
        ListNode(SymbolNode("pc"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("UInt32"), ), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x2), 
          SymbolNode("ldloca.s"), 
          ListNode(SymbolNode("variable"), 
            UnsignedNode(0x1), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Nullable`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), ), ), 
        ListNode(SignedNode(0x4), 
          SymbolNode("initobj"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("Nullable`1"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), ), ), 
        ListNode(SignedNode(0xA), 
          SymbolNode("ldloc.1"), ), 
        ListNode(SignedNode(0xB), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Cpu`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), 
            ListNode(SymbolNode("IFetch"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Nullable`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("!0"), ), ), ), ), 
        ListNode(SignedNode(0x10), 
          SymbolNode("stloc.0"), ), 
        ListNode(SignedNode(0x11), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x12), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x13), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            ListNode(SymbolNode("Parse"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), ), ), 
        ListNode(SignedNode(0x18), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Cpu`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), 
            ListNode(SymbolNode("TryExecute"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("IType"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Boolean"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), ), ), 
        ListNode(SignedNode(0x1D), 
          SymbolNode("stloc.2"), ), 
        ListNode(SignedNode(0x1E), 
          SymbolNode("ldloc.2"), ), 
        ListNode(SignedNode(0x1F), 
          SymbolNode("brfalse.s"), 
          SignedNode(0x25), ), 
        ListNode(SignedNode(0x21), 
          SymbolNode("ldc.i4.1"), ), 
        ListNode(SignedNode(0x22), 
          SymbolNode("stloc.3"), ), 
        ListNode(SignedNode(0x23), 
          SymbolNode("br.s"), 
          SignedNode(0x5B), ), 
        ListNode(SignedNode(0x25), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x26), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x27), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            ListNode(SymbolNode("Parse"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), ), ), 
        ListNode(SignedNode(0x2C), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Cpu`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), 
            ListNode(SymbolNode("TryExecute"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("RType"), ), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Boolean"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!!0"), ), ), ), 
        ListNode(SignedNode(0x31), 
          SymbolNode("stloc.s"), 
          ListNode(SymbolNode("variable"), 
            UnsignedNode(0x4), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Boolean"), ), ), ), 
        ListNode(SignedNode(0x33), 
          SymbolNode("ldloc.s"), 
          ListNode(SymbolNode("variable"), 
            UnsignedNode(0x4), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Boolean"), ), ), ), 
        ListNode(SignedNode(0x35), 
          SymbolNode("brfalse.s"), 
          SignedNode(0x3B), ), 
        ListNode(SignedNode(0x37), 
          SymbolNode("ldc.i4.1"), ), 
        ListNode(SignedNode(0x38), 
          SymbolNode("stloc.3"), ), 
        ListNode(SignedNode(0x39), 
          SymbolNode("br.s"), 
          SignedNode(0x5B), ), 
        ListNode(SignedNode(0x3B), 
          SymbolNode("ldstr"), 
          StringNode("Unhandled instruction: {0: X8} {1}"), ), 
        ListNode(SignedNode(0x40), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x41), 
          SymbolNode("box"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("UInt32"), ), ), 
        ListNode(SignedNode(0x46), 
          SymbolNode("ldloc.0"), ), 
        ListNode(SignedNode(0x47), 
          SymbolNode("box"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("UInt32"), ), ), 
        ListNode(SignedNode(0x4C), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("String"), ), 
            ListNode(SymbolNode("Format"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("String"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("String"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Object"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Object"), ), ), ), 
        ListNode(SignedNode(0x51), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Console"), ), 
            ListNode(SymbolNode("WriteLine"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("String"), ), ), ), 
        ListNode(SignedNode(0x56), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x57), 
          SymbolNode("ldc.i4.0"), ), 
        ListNode(SignedNode(0x58), 
          SymbolNode("stloc.3"), ), 
        ListNode(SignedNode(0x59), 
          SymbolNode("br.s"), 
          SignedNode(0x5B), ), 
        ListNode(SignedNode(0x5B), 
          SymbolNode("ldloc.3"), ), 
        ListNode(SignedNode(0x5C), 
          SymbolNode("ret"), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode("DidOverflow"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Void"), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("ret"), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode("Add"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Void"), ), 
        ListNode(SymbolNode("insn"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("RType"), ), ), ), 
      ListNode(SymbolNode("attribute"), 
        SymbolNode("RTypeAttribute"), 
        UnsignedNode(0x20), 
        StringNode("add %$rd, %$rs, %$rt"), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x2), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("PsxCpu"), ), 
            SymbolNode("Gpr"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("PsxRegs"), ), ), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("ldarg.1"), ), 
        ListNode(SignedNode(0x8), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Rd"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0xD), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0xE), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("PsxCpu"), ), 
            SymbolNode("Gpr"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("PsxRegs"), ), ), ), 
        ListNode(SignedNode(0x13), 
          SymbolNode("ldarg.1"), ), 
        ListNode(SignedNode(0x14), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Rs"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x19), 
          SymbolNode("callvirt"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Registers`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), 
            ListNode(SymbolNode("get_Item"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), ), ), 
        ListNode(SignedNode(0x1E), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("ToSigned"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), ), ), 
        ListNode(SignedNode(0x23), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x24), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("PsxCpu"), ), 
            SymbolNode("Gpr"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("PsxRegs"), ), ), ), 
        ListNode(SignedNode(0x29), 
          SymbolNode("ldarg.1"), ), 
        ListNode(SignedNode(0x2A), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("RType"), ), 
            SymbolNode("Rt"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x2F), 
          SymbolNode("callvirt"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Registers`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), 
            ListNode(SymbolNode("get_Item"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), ), ), 
        ListNode(SignedNode(0x34), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("ToSigned"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), ), ), 
        ListNode(SignedNode(0x39), 
          SymbolNode("add.ovf"), ), 
        ListNode(SignedNode(0x3A), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("ToUnsigned"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x3F), 
          SymbolNode("callvirt"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Registers`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), 
            ListNode(SymbolNode("set_Item"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!0"), ), ), ), 
        ListNode(SignedNode(0x44), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x45), 
          SymbolNode("ret"), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode("AddI"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Void"), ), 
        ListNode(SymbolNode("insn"), 
          ListNode(SymbolNode("type"), 
            SymbolNode("IType"), ), ), ), 
      ListNode(SymbolNode("attribute"), 
        SymbolNode("ITypeAttribute"), 
        UnsignedNode(0x8), 
        StringNode("addi %$rt, %$rs, $imm"), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x2), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("PsxCpu"), ), 
            SymbolNode("Gpr"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("PsxRegs"), ), ), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("ldarg.1"), ), 
        ListNode(SignedNode(0x8), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            SymbolNode("Rt"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0xD), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0xE), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("PsxCpu"), ), 
            SymbolNode("Gpr"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("PsxRegs"), ), ), ), 
        ListNode(SignedNode(0x13), 
          SymbolNode("ldarg.1"), ), 
        ListNode(SignedNode(0x14), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            SymbolNode("Rs"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Byte"), ), ), ), 
        ListNode(SignedNode(0x19), 
          SymbolNode("callvirt"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Registers`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), 
            ListNode(SymbolNode("get_Item"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!0"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), ), ), 
        ListNode(SignedNode(0x1E), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("ToSigned"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), ), ), 
        ListNode(SignedNode(0x23), 
          SymbolNode("ldarg.1"), ), 
        ListNode(SignedNode(0x24), 
          SymbolNode("ldfld"), 
          ListNode(SymbolNode("field"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("IType"), ), 
            SymbolNode("Imm"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt16"), ), ), ), 
        ListNode(SignedNode(0x29), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("ToSigned"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int16"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt16"), ), ), ), 
        ListNode(SignedNode(0x2E), 
          SymbolNode("add.ovf"), ), 
        ListNode(SignedNode(0x2F), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Extensions"), ), 
            ListNode(SymbolNode("ToUnsigned"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Int32"), ), ), ), 
        ListNode(SignedNode(0x34), 
          SymbolNode("callvirt"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Registers`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), 
            ListNode(SymbolNode("set_Item"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("UInt32"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("!0"), ), ), ), 
        ListNode(SignedNode(0x39), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x3A), 
          SymbolNode("ret"), ), ), ), 
    ListNode(SymbolNode("method"), 
      SymbolNode(".ctor"), 
      ListNode(ListNode(SymbolNode("type"), 
          SymbolNode("Void"), ), ), 
      ListNode(SymbolNode("body"), 
        ListNode(SignedNode(0x0), 
          SymbolNode("ldarg.0"), ), 
        ListNode(SignedNode(0x1), 
          SymbolNode("call"), 
          ListNode(SymbolNode("method"), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Cpu`1"), 
              ListNode(SymbolNode("type"), 
                SymbolNode("UInt32"), ), ), 
            ListNode(SymbolNode(".ctor"), ), 
            ListNode(SymbolNode("type"), 
              SymbolNode("Void"), ), ), ), 
        ListNode(SignedNode(0x6), 
          SymbolNode("nop"), ), 
        ListNode(SignedNode(0x7), 
          SymbolNode("ret"), ), ), ), ), )
